version: "3.8"

services:

#  allure:
#    image: "frankescobar/allure-docker-service:2.17.2"
#    environment:
#      CHECK_RESULTS_EVERY_SECONDS: ${CHECK_RESULTS_EVERY_SECONDS}
#      KEEP_HISTORY: ${KEEP_HISTORY}
#      KEEP_HISTORY_LATEST: ${KEEP_HISTORY_LATEST}
#    ports:
#      - ${ALLURE_DOCKER_SERVICE_API_PORT}:5050
#    volumes:
#      - ${PWD}/projects:/app/projects
#
#  allure-ui:
#    image: "frankescobar/allure-docker-service-ui:7.0.3"
#    environment:
#      ALLURE_DOCKER_PUBLIC_API_URL: "http://allure:5050"
#      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
#    ports:
#      - ${ALLURE_DOCKER_SERVICE_UI_PORT}:5252

  allure:
    image: "frankescobar/allure-docker-service:latest"
    user: 1000:1000
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 50
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/projects:/app/projects

  allure-ui:
    image: "frankescobar/allure-docker-service-ui:latest"
    user: 1000:1000
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
