stages:
  - deploy

.ssh-base:
  image: docker:20.10.7-git
  before_script:
    - apk add --no-cache docker-compose rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

### Deployment jobs ###

allure-server:
  stage: deploy
  extends: .ssh-base
  tags:
    - common-170
  variables:
    SSH_PRIVATE_KEY: $SSH_AMD_PRIVATE_KEY_89
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
  script:
    - rsync -avzP ./allure-server/ $SSH_USER_HOSTKEY@$SSH_MACHINE_HOSTKEY:~/allure-server
    - ssh $SSH_USER_HOSTKEY@$SSH_MACHINE_HOSTKEY "cd ~/allure-server && docker-compose down && docker-compose up -d"

deploy-selenoid:
  stage: deploy
  extends: .ssh-base
  tags:
    - common-170
  variables:
    SSH_PRIVATE_KEY: $SSH_AMD_PRIVATE_KEY_244
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
  script:
    - scp -r -o StrictHostKeyChecking=no ./selenoid $SSH_USER_HOSTKEY@$SSH_MACHINE_HOSTKEY:~
    - ssh $SSH_USER_HOSTKEY@$SSH_MACHINE_HOSTKEY "export LIMIT=1 && cd ~/selenoid && docker-compose down && docker-compose rm -f && docker-compose up -d"
    - ssh $SSH_USER_HOSTKEY@$SSH_MACHINE_HOSTKEY "cat ~/selenoid/config/browsers.json  | jq -r '..|.image?|strings' | xargs -I{} docker pull {}"